This Sage Jupyter Notebook is used to verify the stationarity of proposed lattices

In [1]:
import numpy as np

In [2]:
# helper functions for loading lattice data

def getGramNumpy(dim,k):
    # for given dimension and k, return the Gram matrix as a numpy array
    kappa = 2*np.ceil(k/2).astype(int)
    a = 2*kappa**2
    b = kappa**2
    c = -4
    G8 = np.array([[a, b, b, 0, b, 0, b, c],
                   [b, a, 0, 0, 0, 0, b, c], 
                   [b, 0, a, 0, b, 0, 0, 0],
                   [0, 0, 0, a,-b, b,-b, 0],
                   [b, 0, b,-b, a, 0, b, 0],
                   [0, 0, 0, b, 0, a,-b, 0],
                   [b, b, 0,-b, b,-b, a, c],
                   [c, c, 0, 0, 0, 0, c, 8]])     
    return G8[8-dim:8,8-dim:8]


def getGramSage(dim):
    # for given dimension, return the Gram matrix as a Sage matrix
    var('kappa')
    a = 2*kappa**2
    b = kappa**2
    c = -4
    G = matrix(SR,8,[a, b, b, 0, b, 0, b, c,
                       b, a, 0, 0, 0, 0, b, c, 
                       b, 0, a, 0, b, 0, 0, 0,
                       0, 0, 0, a,-b, b,-b, 0,
                       b, 0, b,-b, a, 0, b, 0,
                       0, 0, 0, b, 0, a,-b, 0,
                       b, b, 0,-b, b,-b, a, c,
                       c, c, 0, 0, 0, 0, c, 8])    
    return G[8-dim:8,8-dim:8]


def getLattVecsNumpy(dim,k):
    # for given dimension and k, return the lattice vectors as a numpy array
    LattVecs = np.zeros([8,120],dtype=int)
    
    # dimension 2
    v2 = np.array([[0,np.ceil(k/2)],[1,0],[1,1]]).transpose()
    LattVecs[-2:,0:3] = v2
    if dim==2: return LattVecs[-dim:,:3]

    # dimension 3
    v3 = np.array([[1,0,0],[1,1,0],[1,1,1]]).transpose()
    LattVecs[-3:,3:6] = v3
    if dim==3: return LattVecs[-dim:,:6]

    # dimension 4
    v4 = np.array([[1,0,0,0],[1,0,-1,0],[1,-1,-1,0],[1,0,-1,-1],[1,-1,-1,-1]]).transpose()
    v4k1 = np.array([1,-1,-2,-1]).transpose()
    if k>=3: 
        LattVecs[-4:,6:11] = v4
        if dim==4: return LattVecs[-dim:,:11]
    else: 
        LattVecs[-4:,6:11] = v4
        LattVecs[-4:,11] = v4k1    
        if dim==4: return LattVecs[-dim:,:12]

    # dimension 5
    v5 = np.array([[1,0,0,0,0],[1,0,-1,0,0],[1,1,-1,0,0],[1,1,0,0,0],[1,0,0,1,1],[1,0,0,1,0],[1,1,-1,-1,-1],
                   [1,1,-1,-1,0]]).transpose()
    if k>=3: 
        LattVecs[-5:,11:19] = v5
        if dim==5: return LattVecs[-dim:,:19]
    else: 
        LattVecs[-5:,12:20] = v5
        if dim==5: return LattVecs[-dim:,:20]

    # dimension 6
    v6 = np.array([[1,0,0,0,0,0],[1,-1,-1,1,0,0],[1,0,-1,0,0,0],[1,-1,-1,0,0,0],[1,0,-1,0,1,1],[1,0,-1,0,1,0],[1,0,-1,1,1,1],[1,-1,-1,1,1,1],[1,0,-1,1,1,0],
                  [1,-1,-1,1,1,0],[1,-1,-2,1,1,1],[1,-1,-2,1,1,0]]).transpose()
    v6k1 = np.array([[1,-1,-2,2,2,1],[1,0,-1,1,2,1],[1,0,-2,1,2,1],[1,-1,-2,1,2,1]]).transpose()
    if k>=3: 
        LattVecs[-6:,19:31] = v6
        if dim==6: return LattVecs[-dim:,:31]
    else: 
        LattVecs[-6:,20:32] = v6
        LattVecs[-6:,32:36] = v6k1            
        if dim==6: return LattVecs[-dim:,:36]
    
    # dimension 7
    v7 = np.array([[1,0,0,0,0,0,0],[1,0,0,0,-1,-1,0],[1,0,0,0,0,-1,0],[1,0,-1,0,0,-1,0],[1,0,0,1,0,-1,0],[1,-1,0,1,0,-1,0],
                   [1,0,0,1,-1,-1,0],[1,-1,0,1,-1,-1,0],[1,0,1,1,-1,-1,0],[1,-1,1,1,-1,-1,0],[1,-1,1,2,-1,-1,0],
                   [1,0,0,1,-1,-2,0],[1,-1,0,1,-1,-2,0],[1,0,0,1,-1,-2,-1],[1,-1,0,1,-1,-2,-1],
                   [1,-1,1,2,-2,-2,0],[1,-1,1,2,-2,-2,-1],[1,0,0,0,0,0,1],
                   [1,-1,0,2,-1,-2,0],[1,-1,1,2,-1,-2,0],
                   [1,-1,0,2,-1,-2,-1],[1,-1,1,2,-1,-2,-1]]).transpose()
    v7k1 = np.array([[1,-2,1,3,-2,-3,-1],[1,-1,1,2,-2,-3,-1],[1,-1,0,2,-2,-3,-1],
                     [1,-1,0,2,-1,-3,-1],[1,-1,1,3,-2,-3,-1]]).transpose()
    if k>=3: 
        LattVecs[-7:,31:53] = v7
        if dim==7: return LattVecs[-dim:,:53]
    else: 
        LattVecs[-7:,36:58] = v7
        LattVecs[-7:,58:63] = v7k1            
        if dim==7: return LattVecs[-dim:,:63]
    
    # dimension 8
    v8 = np.array([[1,0,0,0,0,0,0,0],[1,0,0,-1,-1,0,-1,0],[1,0,0,0,0,-1,-1,0],[1,1,-1,0,1,-1,-2,0],
                   [1,0,0,0,0,0,-1,0],[1,0,0,-1,0,0,-1,0],[1,0,-1,0,0,-1,-1,0],[1,-1,0,-1,-1,1,0,0],
                   [1,-1,0,0,-1,0,0,0],[1,-1,0,-1,-1,0,0,0],[1,0,-1,0,0,0,-1,0],[1,0,-1,-1,0,0,-1,0],
                   [1,-1,-1,0,0,0,0,0],[1,-1,0,0,0,0,0,0],[1,0,-1,0,1,0,-1,0],[1,0,-1,0,1,-1,-1,0],
                   [1,0,-1,1,1,-1,-1,0],
                    [1,-1,0,-1,-2,1,1,0],[1,-1,0,0,-1,0,1,0],[1,-1,0,0,-1,0,1,1],[1,0,-1,0,1,-1,-2,-1],
                    [1,0,-1,0,1,-1,-2,0],[1,-1,0,0,-1,1,1,0],[1,-1,0,-1,-1,1,1,0],[1,-1,0,0,-1,1,1,1],[1,-1,0,-1,-1,1,1,1],
                    [1,0,0,-1,-1,1,0,0],[1,-1,0,-1,-2,1,1,1],[1,0,0,0,-1,0,0,0],[1,0,0,-1,-1,0,0,0],[1,0,0,0,0,0,0,1],
                    [1,0,-1,0,0,0,0,0],[1,0,0,-1,-1,1,0,1],[1,0,0,0,-1,0,0,1],[1,0,0,-1,-1,0,0,1],[1,0,-1,0,0,0,0,1],
                    [1,-1,1,-1,-2,1,1,0],[1,-1,1,-1,-2,1,1,1]]).transpose()
    v8k1 = np.array([[1,-1,0,0,-1,1,2,1],[1,-1,1,-1,-3,2,2,1],[1,-1,1,-2,-3,2,2,1],[1,-1,0,0,-2,1,2,1],[1,0,1,-1,-2,1,1,1],
                      [1,-1,0,-1,-2,2,2,1],[1,0,0,0,-1,0,1,1],[1,-1,1,0,-2,1,2,1],[1,0,0,-1,-2,1,1,1],[1,0,0,-1,-1,1,1,1],
                      [1,-1,1,-1,-3,2,3,1],[1,-2,1,-1,-3,2,3,1],[1,-1,1,-1,-3,2,3,2],[1,-1,1,-1,-2,2,2,1],[1,-1,1,-1,-3,1,2,1],
                      [1,0,0,0,-1,1,1,1],[1,-1,0,-1,-2,1,2,1],[1,-1,1,-1,-2,1,2,1],[2,-1,0,-1,-2,1,1,1]]).transpose()
    if k>=3: 
        LattVecs[-8:,53:91] = v8
        if dim==8: return LattVecs[-dim:,:91]
    else: 
        LattVecs[-8:,63:101] = v8
        LattVecs[-8:,101:120] = v8k1            
        if dim==8: return LattVecs[-dim:,:120]
           
    return None


def getLattVecsSage(dim,k1=False):
    # For given dimension, return the lattice vectors as a Sage array
    # Set k1 = True for k=1,2 and False for k>2
    # We first use getLattVecsNumpy and then overwrite 
    # the single lattice vector that depends on k
    if k1: 
        LattVecs_np = getLattVecsNumpy(dim=dim,k=1)
    else: 
        LattVecs_np = getLattVecsNumpy(dim=dim,k=3)
    
    mult = LattVecs_np.shape[1] # half multiplicity     
    LattVecs = matrix(SR, dim, mult, LattVecs_np.flatten().tolist())
    
    if not k1: LattVecs[-1,0] = kappa/2
    
    return LattVecs, mult


def getStatVecSage(dim,k1):
    # for given dimension, return the vector c used in the stationarity condition as a Sage vector
    # Set k1 = True for k=1,2 and False for k>2

    if k1: 
        mult = getLattVecsNumpy(dim=dim,k=1).shape[1]
        c = vector(SR,mult,np.ones(mult,dtype='int').tolist())
        return c 
    
    mult = getLattVecsNumpy(dim=dim,k=3).shape[1]    
    c = vector(SR,mult,np.ones(mult,dtype='int').tolist())
       
    
    var('kappa')
    inds = [3, 6, 11,12,13,14, 19,20,21,22, 
            32,33,34,35,36,37,38,39,40,41, 
            54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69] 

    if dim==2:
        a = (2*kappa**2 - 4) / kappa**2
        b = np.nan 
        inds = []
    if dim==3:
        a = (3*kappa**2 - 8) / kappa**2
        b = (2*kappa**2 - 4) / kappa**2
        inds = inds[:1]
    if dim==4:
        a = 4*(kappa**2 - 4) / kappa**2
        b = 2*(kappa**2 - 4) / kappa**2
        inds = inds[:2]
    if dim==5:
        a = 6*(kappa**2 - 4) / kappa**2
        b = 2*(kappa**2 - 3) / kappa**2
        inds = inds[:6]
    if dim==6: 
        a = 8*(kappa**2 - 5) / kappa**2
        b = 2*(kappa**2 - 4) / kappa**2
        inds = inds[:10]
    if dim==7: 
        a = 4*(3*kappa**2 - 16) / kappa**2
        b = 2*(kappa**2 - 4) / kappa**2
        inds = inds[:20]
    if dim==8: 
        a = 18*(kappa**2 - 6) / kappa**2
        b = (2* kappa**2 - 9) / kappa**2

    c[0] = a
    for i in inds: c[i] = b
    return c


In [3]:
# First check stationarity condition holds for k = 1
for dim in range(2,9): 
    print(dim)
    G = getGramSage(dim)
    G = G.subs(kappa == 2)
    G_inv = G.inverse()
    G_det = G.det()

    LattVecs,mult = getLattVecsSage(dim,k1=True)
    c = getStatVecSage(dim,k1=True)
    print(mult)
    
    Ms = zero_matrix(SR, dim);
    for ii in range(mult):
        v = LattVecs[:,ii]
        v_len = (v.T*G*v)[0,0]
        if v_len - 8: print(f'Wrong eigenvalue: dim = {dim}, ii = {ii}')
        Lam = 4*pi**2*G_det**(-1/dim)*v_len
        outer = matrix(SR,dim,[a*b for a in v for b in v])
        M = -Lam/dim*G_inv + 4*pi**2*G_det**(-1/dim)*outer
        Ms = Ms + c[ii]*M  

    for ii in range(dim):
        for jj in range(dim):
            Ms[ii,jj]=Ms[ii,jj].full_simplify()

    print(Ms)

2
3
[0 0]
[0 0]
3
6
[0 0 0]
[0 0 0]
[0 0 0]
4
12
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
5
20
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
6
36
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
7
63
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
8
120
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]


In [4]:
# Now check stationarity condition holds for k > 2
for dim in range(2,9): 
    print(dim)
    G = getGramSage(dim)
    G_inv = G.inverse()
    G_det = G.det()
    print(G_det)

    LattVecs,mult = getLattVecsSage(dim,k1=False)
    c = getStatVecSage(dim,k1=False)

    
    Ms = zero_matrix(SR, dim);
    for ii in range(mult):
        v = LattVecs[:,ii]
        v_len = (v.T*G*v)[0,0]
        if v_len - 2*kappa^2: print(f'Wrong eigenvalue: dim = {dim}, ii = {ii}')
        Lam = 4*pi**2*G_det**(-1/dim)*v_len
        outer = matrix(SR,dim,[a*b for a in v for b in v])
        M = -Lam/dim*G_inv + 4*pi**2*G_det**(-1/dim)*outer
        Ms = Ms + c[ii]*M  

    for ii in range(dim):
        for jj in range(dim):
            Ms[ii,jj]=Ms[ii,jj].full_simplify()

    print(Ms)

2
16*kappa^2 - 16
[0 0]
[0 0]
3
-8*kappa^4 + 32*(kappa^2 - 1)*kappa^2
[0 0 0]
[0 0 0]
[0 0 0]
4
32*kappa^6 - 64*kappa^4
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
5
32*kappa^8 - 64*kappa^6
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
6
32*kappa^10 - 80*kappa^8
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
7
24*kappa^12 - 64*kappa^10
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
8
16*kappa^14 - 48*kappa^12
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
